// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcjshpoqlldwpfsellxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjanNocG9xbGxkd3Bmc2VsbHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODE2OTksImV4cCI6MjA1OTI1NzY5OX0.BfOkEml8AX-uvSdYH5a94BJ8Wy_0jC73hpRtvquJ9zk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);